// <auto-generated />
using System;
using FreeKSeF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FreeKSeF.Data.Migrations
{
    [DbContext(typeof(FreeKSeFDbContext))]
    [Migration("20260606153122_Ustawienia")]
    partial class Ustawienia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FreeKSeF.Data.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresL1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdresL2")
                        .HasColumnType("TEXT");

                    b.Property<string>("KodKraju")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KsefTokenProtected")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NrRachunku")
                        .HasColumnType("TEXT");

                    b.Property<int>("Srodowisko")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UtworzonoUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("FreeKSeF.Data.Entities.Contractor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdresL1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdresL2")
                        .HasColumnType("TEXT");

                    b.Property<string>("KodKraju")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nip")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UtworzonoUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nip");

                    b.ToTable("Contractors");
                });

            modelBuilder.Entity("FreeKSeF.Data.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataSprzedazy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataWystawienia")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kierunek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KontrahentNazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KontrahentNip")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumerKsef")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumerReferencyjny")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SumaBrutto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SumaNetto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SumaVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("UpoXml")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UtworzonoUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Waluta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("WyslanoUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NumerKsef");

                    b.HasIndex("Kierunek", "DataWystawienia");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("FreeKSeF.Data.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CenaNetto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Ilosc")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jednostka")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("KwotaVat")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Lp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stawka")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WartoscNetto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("FreeKSeF.Data.Entities.KsefLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CzasUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Komunikat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operacja")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Poziom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KsefLogs");
                });

            modelBuilder.Entity("FreeKSeF.Data.Entities.Ustawienie", b =>
                {
                    b.Property<string>("Klucz")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wartosc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Klucz");

                    b.ToTable("Ustawienia");
                });

            modelBuilder.Entity("FreeKSeF.Data.Entities.InvoiceItem", b =>
                {
                    b.HasOne("FreeKSeF.Data.Entities.Invoice", "Invoice")
                        .WithMany("Pozycje")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("FreeKSeF.Data.Entities.Invoice", b =>
                {
                    b.Navigation("Pozycje");
                });
#pragma warning restore 612, 618
        }
    }
}
